/-
  ArithmeticBridge.lean — The divisibility lattice as a causal algebra

  This file constructs the divisibility causal algebra and connects it to
  Mathlib's number-theoretic Möbius function. The Möbius function identities
  (`mu_one`, `mu_prime`, `mu_ne_zero_iff`, `mu_of_squarefree`,
  `moebius_times_zeta_eq_one`) are thin wrappers around Mathlib lemmas.
  The novel content is the CSpec construction:
  - `divCAlg`: the causal algebra of divisors of n
  - `primeUpset_complement_convex`: complement of a prime upset is causally convex
  - `prime_gives_CSpec_point`: primes give CSpec points of divCAlg
-/
import Mathlib.NumberTheory.ArithmeticFunction.Moebius
import Mathlib.Combinatorics.Enumerative.IncidenceAlgebra
import Mathlib.Data.Nat.Prime.Basic
import CausalAlgebraicGeometry.CausalAlgebra
import CausalAlgebraicGeometry.CausalPrimality

namespace CausalAlgebraicGeometry.ArithmeticBridge

open CausalAlgebra CausalPrimality

/-! ### The divisibility causal algebra -/

/-- The **divisibility causal algebra** on the divisors of n.
    Elements are the positive divisors of n, ordered by divisibility.
    This is a finite causal set — the "local" piece of (ℤ⁺, |). -/
def divCAlg (n : ℕ) (hn : 0 < n) : CAlg ℚ where
  Λ := {d : ℕ // d ∈ n.divisors}
  le := fun a b => (a : ℕ) ∣ (b : ℕ)
  le_refl := fun a => dvd_refl (a : ℕ)
  le_antisymm := fun a b hab hba => by
    ext; exact Nat.dvd_antisymm hab hba
  le_trans := fun a b c hab hbc => dvd_trans hab hbc

/-! ### Key values of the number-theoretic Möbius function -/

/-- μ(1) = 1: the identity element. -/
theorem mu_one : ArithmeticFunction.moebius 1 = 1 :=
  ArithmeticFunction.moebius_apply_one

/-- μ(p) = -1 for any prime p. -/
theorem mu_prime (p : ℕ) (hp : p.Prime) : ArithmeticFunction.moebius p = -1 :=
  ArithmeticFunction.moebius_apply_prime hp

/-- μ(n) ≠ 0 ↔ n is squarefree. This is the characterization that
    connects the Möbius function to the multiplicative structure. -/
theorem mu_ne_zero_iff (n : ℕ) :
    ArithmeticFunction.moebius n ≠ 0 ↔ Squarefree n :=
  ArithmeticFunction.moebius_ne_zero_iff_squarefree

/-- μ(n) for squarefree n equals (-1)^ω(n) where ω is the number
    of prime factors. -/
theorem mu_of_squarefree {n : ℕ} (h : Squarefree n) :
    ArithmeticFunction.moebius n =
      (-1 : ℤ) ^ (ArithmeticFunction.cardFactors n) :=
  ArithmeticFunction.moebius_apply_of_squarefree h

/-! ### The Möbius inversion identity -/

/-- **Möbius inversion**: μ * ζ = 1 in the arithmetic function ring.
    This is Mathlib's `moebius_mul_coe_zeta`, the foundation of
    Möbius inversion. Evaluating at n gives Σ_{d|n} μ(d) = [n=1]. -/
theorem moebius_times_zeta_eq_one :
    ArithmeticFunction.moebius * ↑ArithmeticFunction.zeta = 1 :=
  ArithmeticFunction.moebius_mul_coe_zeta

/-- **Möbius sum (antidiagonal form)**: (μ * ζ)(n) = [n=1].
    This is the direct evaluation of μ * ζ = 1 at n. -/
theorem moebius_mul_zeta_eq (n : ℕ) :
    (ArithmeticFunction.moebius * ↑ArithmeticFunction.zeta) n =
      if n = 1 then 1 else 0 := by
  rw [moebius_times_zeta_eq_one]; rfl

/-! ### Primes as causally prime ideals -/

/-- In the divisibility poset of n, the **upset generated by a prime p**
    (with p | n) consists of all divisors of n that are divisible by p. -/
def primeUpset (n p : ℕ) : Set {d : ℕ // d ∈ n.divisors} :=
  {d | (p : ℕ) ∣ (d : ℕ)}

/-- The prime upset is an upset in the divisibility order:
    if p | a and a | b, then p | b. -/
theorem primeUpset_isUpset (n p : ℕ) (hn : 0 < n) :
    IsUpset (divCAlg n hn) (primeUpset n p) := by
  intro a b ha hab
  exact dvd_trans ha hab

/-- The complement of a prime upset is causally convex:
    if a | c | b, p ∤ a, p ∤ b, then p ∤ c.
    Proof: c | b and p | c would give p | b, contradicting p ∤ b. -/
theorem primeUpset_complement_convex (n p : ℕ) (hn : 0 < n) :
    IsCausallyConvex (divCAlg n hn) (primeUpset n p)ᶜ := by
  intro a b c ha hb hac hcb
  simp only [Set.mem_compl_iff, primeUpset, Set.mem_setOf_eq] at ha hb ⊢
  -- hac : a | c, hcb : c | b, hb : p ∤ b
  -- If p | c then p | b (since c | b), contradicting hb
  intro hpc
  exact hb (dvd_trans hpc hcb)

/-- For a prime p dividing n, the prime upset is a proper subset
    (since 1 | n and p ∤ 1 for any prime p ≥ 2). -/
theorem primeUpset_proper (n p : ℕ) (hn : 0 < n) (hp : p.Prime) :
    primeUpset n p ≠ Set.univ := by
  intro h
  -- 1 ∈ n.divisors since n > 0
  have h1 : 1 ∈ n.divisors := Nat.mem_divisors.mpr ⟨one_dvd n, by omega⟩
  -- So ⟨1, h1⟩ ∈ primeUpset, meaning p | 1
  have : (⟨1, h1⟩ : {d : ℕ // d ∈ n.divisors}) ∈ primeUpset n p :=
    h ▸ Set.mem_univ _
  simp only [primeUpset, Set.mem_setOf_eq] at this
  -- p | 1 contradicts p ≥ 2
  -- p | 1 implies p ≤ 1, contradicting p.Prime (p ≥ 2)
  have hp1 : p ≤ 1 := Nat.le_of_dvd Nat.one_pos this
  exact absurd hp1 (by exact Nat.not_le.mpr hp.one_lt)

/-! ### CSpec recovers the primes -/

/-- **Recovery of Spec(ℤ)**: for each prime p | n, the prime upset
    gives a point of CSpec(divCAlg n). As n → ∞ (or n = lcm of all
    primes up to N), CSpec contains all primes up to N.

    This is how the causal spectrum CSpec of the divisibility algebra
    recovers the prime spectrum Spec(ℤ). -/
theorem prime_gives_CSpec_point (n p : ℕ) (hn : 0 < n) (hp : p.Prime)
    (hpn : p ∣ n) :
    IsCausallyPrime (divCAlg n hn) (primeUpset n p) where
  proper := primeUpset_proper n p hn hp
  upset := primeUpset_isUpset n p hn
  complement_convex := primeUpset_complement_convex n p hn

/-! ### The complete arithmetic bridge -/

/-- Summary of the arithmetic bridge: the divisibility lattice is a causal
    algebra, Mathlib's Möbius identities apply, and primes give CSpec points.

    Components 1–4 are Mathlib re-exports; component 5 (`prime_gives_CSpec_point`)
    is the novel contribution of this file. -/
theorem arithmetic_bridge (n : ℕ) (hn : 0 < n) :
    -- μ * ζ = 1
    (ArithmeticFunction.moebius * ↑ArithmeticFunction.zeta = 1) ∧
    -- (μ * ζ)(n) = [n=1]
    ((ArithmeticFunction.moebius * ↑ArithmeticFunction.zeta) n =
      if n = 1 then 1 else 0) ∧
    -- μ(1) = 1
    (ArithmeticFunction.moebius 1 = 1) ∧
    -- μ(p) = -1 for primes
    (∀ p, p.Prime → ArithmeticFunction.moebius p = -1) ∧
    -- Primes give CSpec points
    (∀ p, p.Prime → p ∣ n → IsCausallyPrime (divCAlg n hn) (primeUpset n p)) :=
  ⟨moebius_times_zeta_eq_one,
   moebius_mul_zeta_eq n,
   mu_one,
   fun p hp => mu_prime p hp,
   fun p hp hpn => prime_gives_CSpec_point n p hn hp hpn⟩

end CausalAlgebraicGeometry.ArithmeticBridge
