/-
# The exact cluster representation of weak-ordering entropy

Sort two antitone profiles pointwise. On every connected disagreement
region, one binary choice records which input profile owns the lower
boundary. These choices are independent between regions. Consequently
the sorting fiber has cardinality 2^c, and H^2 = sum_(lower <= upper) 2^c.

The components below are the equivalence classes generated by overlap
along comparable base points. This is an exact finite switching identity,
not an area estimate or a gravitational model.
-/
import CausalAlgebraicGeometry.CAGCompatibilityEntropy
import Mathlib.Analysis.Convex.SpecificFunctions.Basic
import Mathlib.Analysis.Convex.Jensen
import Mathlib.Order.Interval.Finset.Basic

namespace CausalAlgebraicGeometry.CAGOrderingClusters

open C3OrderIdealReduction CAGCompatibilityEntropy CAGMultidimensionalEntropy

noncomputable section
open scoped Classical

def sortProfiles {d m : ℕ} (p : TrimmedProfile d m × TrimmedProfile d m) :
    WeakOrderedPair d m where
  lower x := min (p.1.val x) (p.2.val x)
  upper x := max (p.1.val x) (p.2.val x)
  lower_antitone := p.1.property.inf p.2.property
  upper_antitone := p.1.property.sup p.2.property
  lower_le_upper _ := (min_le_left _ _).trans (le_max_left _ _)

def SortingFiber {d m : ℕ} (w : WeakOrderedPair d m) :=
  { p : TrimmedProfile d m × TrimmedProfile d m // sortProfiles p = w }

instance {d m : ℕ} (w : WeakOrderedPair d m) : Fintype (SortingFiber w) := by
  unfold SortingFiber
  infer_instance

def DisagreementPoint {d m : ℕ} (w : WeakOrderedPair d m) :=
  { x : Fin d → Fin m // w.lower x < w.upper x }

instance {d m : ℕ} (w : WeakOrderedPair d m) : Fintype (DisagreementPoint w) := by
  unfold DisagreementPoint
  infer_instance

/-- A causal comparison forces the same ownership bit precisely when
the two nonempty height intervals overlap. -/
def Overlap {d m : ℕ} (w : WeakOrderedPair d m)
    (a b : DisagreementPoint w) : Prop :=
  (a.val ≤ b.val ∧ w.lower a.val < w.upper b.val) ∨
    (b.val ≤ a.val ∧ w.lower b.val < w.upper a.val)

/-- Immediate causal comparisons suffice to enforce all ownership
constraints. This is locality of the constraint, not of the resulting
entropy: connected regions can still extend across the entire box. -/
theorem overlap_invariance_iff_cover_invariance {d m : ℕ} (w : WeakOrderedPair d m)
    (f : DisagreementPoint w → Bool) :
    (∀ a b, Overlap w a b → f a = f b) ↔
      (∀ a b, a.val ⋖ b.val → w.lower a.val < w.upper b.val → f a = f b) := by
  constructor
  · intro h a b hab hov
    exact h a b (Or.inl ⟨hab.le, hov⟩)
  · intro hlocal
    letI : LocallyFiniteOrder (Fin d → Fin m) := Fintype.toLocallyFiniteOrder
    have hpath : ∀ {x y : Fin d → Fin m}, Relation.ReflTransGen (· ⋖ ·) x y →
        ∀ (hx : w.lower x < w.upper x) (hy : w.lower y < w.upper y),
          w.lower x < w.upper y → f ⟨x, hx⟩ = f ⟨y, hy⟩ := by
      intro x y hxy
      induction hxy with
      | refl => intro hx hy _; rfl
      | @tail y z hxy hyz ih =>
        intro hx hz hov
        have hle : x ≤ y := le_iff_reflTransGen_covBy.mpr hxy
        have hov' : w.lower x < w.upper y := hov.trans_le (w.upper_antitone hyz.le)
        have hy : w.lower y < w.upper y := (w.lower_antitone hle).trans_lt hov'
        exact (ih hx hy hov').trans
          (hlocal ⟨y, hy⟩ ⟨z, hz⟩ hyz ((w.lower_antitone hle).trans_lt hov))
    intro a b hab
    rcases hab with ⟨hab, hov⟩ | ⟨hba, hov⟩
    · exact hpath (le_iff_reflTransGen_covBy.mp hab) a.property b.property hov
    · exact (hpath (le_iff_reflTransGen_covBy.mp hba) b.property a.property hov).symm

/-- Quotient by the equivalence relation generated by overlap: the
connected disagreement regions, including single-point components. -/
def BandComponent {d m : ℕ} (w : WeakOrderedPair d m) := Quot (Overlap w)

instance {d m : ℕ} (w : WeakOrderedPair d m) : Finite (BandComponent w) := by
  unfold BandComponent
  infer_instance

instance {d m : ℕ} (w : WeakOrderedPair d m) : Fintype (BandComponent w) :=
  Fintype.ofFinite _

def componentOf {d m : ℕ} {w : WeakOrderedPair d m}
    (a : DisagreementPoint w) : BandComponent w := Quot.mk _ a

def clusterCount {d m : ℕ} (w : WeakOrderedPair d m) : ℕ :=
  Fintype.card (BandComponent w)

theorem fiber_min {d m : ℕ} {w : WeakOrderedPair d m}
    (p : SortingFiber w) (x : Fin d → Fin m) :
    min (p.val.1.val x) (p.val.2.val x) = w.lower x :=
  congrArg (fun z => z.lower x) p.property

theorem fiber_max {d m : ℕ} {w : WeakOrderedPair d m}
    (p : SortingFiber w) (x : Fin d → Fin m) :
    max (p.val.1.val x) (p.val.2.val x) = w.upper x :=
  congrArg (fun z => z.upper x) p.property

theorem fiber_values {d m : ℕ} {w : WeakOrderedPair d m}
    (p : SortingFiber w) (x : Fin d → Fin m) :
    (p.val.1.val x = w.lower x ∧ p.val.2.val x = w.upper x) ∨
      (p.val.1.val x = w.upper x ∧ p.val.2.val x = w.lower x) := by
  have hlo := fiber_min p x
  have hup := fiber_max p x
  rcases le_total (p.val.1.val x) (p.val.2.val x) with h | h
  · exact Or.inl ⟨by simpa [min_eq_left h] using hlo, by simpa [max_eq_right h] using hup⟩
  · exact Or.inr ⟨by simpa [max_eq_left h] using hup, by simpa [min_eq_right h] using hlo⟩

/-- The ownership bit is constant on every generating overlap. -/
theorem ownership_eq_of_overlap {d m : ℕ} {w : WeakOrderedPair d m}
    (p : SortingFiber w) (a b : DisagreementPoint w) (hab : Overlap w a b) :
    (p.val.1.val a.val = w.lower a.val) ↔ (p.val.1.val b.val = w.lower b.val) := by
  have ha := fiber_values p a.val
  have hb := fiber_values p b.val
  have hda := a.property
  have hdb := b.property
  rcases hab with ⟨hab, hov⟩ | ⟨hba, hov⟩
  · have hp := p.val.1.property hab
    have hq := p.val.2.property hab
    rcases ha with ⟨ha1, ha2⟩ | ⟨ha1, ha2⟩ <;>
      rcases hb with ⟨hb1, hb2⟩ | ⟨hb1, hb2⟩ <;> constructor <;> intro h <;> omega
  · have hp := p.val.1.property hba
    have hq := p.val.2.property hba
    rcases ha with ⟨ha1, ha2⟩ | ⟨ha1, ha2⟩ <;>
      rcases hb with ⟨hb1, hb2⟩ | ⟨hb1, hb2⟩ <;> constructor <;> intro h <;> omega

def ownership {d m : ℕ} {w : WeakOrderedPair d m} (p : SortingFiber w) :
    BandComponent w → Bool :=
  Quot.lift (fun a => decide (p.val.1.val a.val = w.lower a.val))
    (by
      intro a b hab
      simp only [ownership_eq_of_overlap p a b hab])

/-- Reconstruct a profile from one ownership bit per connected region.
The Boolean value true chooses the lower boundary. -/
def chooseHeight {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) (x : Fin d → Fin m) : Fin m :=
  if hx : w.lower x < w.upper x then
    if c (componentOf ⟨x, hx⟩) then w.lower x else w.upper x
  else w.lower x

theorem chooseHeight_bounds {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) (x : Fin d → Fin m) :
    w.lower x ≤ chooseHeight w c x ∧ chooseHeight w c x ≤ w.upper x := by
  unfold chooseHeight
  split_ifs <;> simp [w.lower_le_upper x]

theorem chooseHeight_antitone {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) : Antitone (chooseHeight w c) := by
  intro x y hxy
  by_cases hov : w.lower x < w.upper y
  · have hx : w.lower x < w.upper x := hov.trans_le (w.upper_antitone hxy)
    have hy : w.lower y < w.upper y := (w.lower_antitone hxy).trans_lt hov
    have hc : componentOf (w := w) ⟨x, hx⟩ = componentOf ⟨y, hy⟩ :=
      Quot.sound (Or.inl ⟨hxy, hov⟩)
    simp only [chooseHeight, dif_pos hx, dif_pos hy]
    rw [hc]
    split_ifs
    · exact w.lower_antitone hxy
    · exact w.upper_antitone hxy
  · exact (chooseHeight_bounds w c y).2.trans
      ((le_of_not_gt hov).trans (chooseHeight_bounds w c x).1)

def complementaryChoice {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) : TrimmedProfile d m × TrimmedProfile d m :=
  (⟨chooseHeight w c, chooseHeight_antitone w c⟩,
   ⟨chooseHeight w (fun a => !(c a)), chooseHeight_antitone w _⟩)

theorem complementaryChoice_sorts {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) : sortProfiles (complementaryChoice w c) = w := by
  apply WeakOrderedPair.ext <;> funext x
  · change min (chooseHeight w c x) (chooseHeight w (fun a => !(c a)) x) = w.lower x
    by_cases hx : w.lower x < w.upper x
    · simp only [chooseHeight, dif_pos hx]
      by_cases hc : c (componentOf ⟨x, hx⟩) = true <;> simp [hc, min_eq_left (w.lower_le_upper x),
        min_eq_right (w.lower_le_upper x)]
    · simp [chooseHeight, hx]
  · change max (chooseHeight w c x) (chooseHeight w (fun a => !(c a)) x) = w.upper x
    by_cases hx : w.lower x < w.upper x
    · simp only [chooseHeight, dif_pos hx]
      by_cases hc : c (componentOf ⟨x, hx⟩) = true <;> simp [hc, max_eq_left (w.lower_le_upper x),
        max_eq_right (w.lower_le_upper x)]
    · have heq : w.lower x = w.upper x := le_antisymm (w.lower_le_upper x) (le_of_not_gt hx)
      simp [chooseHeight, heq]

def fromOwnership {d m : ℕ} (w : WeakOrderedPair d m)
    (c : BandComponent w → Bool) : SortingFiber w :=
  ⟨complementaryChoice w c, complementaryChoice_sorts w c⟩

theorem fromOwnership_ownership {d m : ℕ} {w : WeakOrderedPair d m}
    (p : SortingFiber w) : fromOwnership w (ownership p) = p := by
  apply Subtype.ext
  apply Prod.ext <;> apply Subtype.ext <;> funext x
  · change chooseHeight w (ownership p) x = p.val.1.val x
    have hv := fiber_values p x
    have horder := w.lower_le_upper x
    by_cases hx : w.lower x < w.upper x
    · simp only [chooseHeight, dif_pos hx, ownership, componentOf,
        decide_eq_true_eq]
      rcases hv with ⟨hlo, hup⟩ | ⟨hup, hlo⟩ <;> split_ifs <;> omega
    · simp only [chooseHeight, dif_neg hx]
      rcases hv with ⟨hlo, hup⟩ | ⟨hup, hlo⟩
      · exact hlo.symm
      · exact (le_antisymm horder (le_of_not_gt hx)).trans hup.symm
  · change chooseHeight w (fun a => !(ownership p a)) x = p.val.2.val x
    have hv := fiber_values p x
    have horder := w.lower_le_upper x
    by_cases hx : w.lower x < w.upper x
    · have hown : ownership p (componentOf (w := w) ⟨x, hx⟩) =
          decide (p.val.1.val x = w.lower x) := rfl
      simp only [chooseHeight, dif_pos hx, hown]
      rcases hv with ⟨hlo, hup⟩ | ⟨hup, hlo⟩
      · simp [hlo, hup]
      · simp [hup, hlo, ne_of_gt hx]
    · simp only [chooseHeight, dif_neg hx]
      rcases hv with ⟨hlo, hup⟩ | ⟨hup, hlo⟩
      · exact (le_antisymm horder (le_of_not_gt hx)).trans hup.symm
      · exact hlo.symm

theorem ownership_fromOwnership {d m : ℕ} {w : WeakOrderedPair d m}
    (c : BandComponent w → Bool) : ownership (fromOwnership w c) = c := by
  funext a
  refine Quot.inductionOn a ?_
  intro x
  change decide (chooseHeight w c x.val = w.lower x.val) = c (componentOf x)
  simp only [chooseHeight, dif_pos x.property]
  cases hc : c (componentOf x) <;> simp [hc, ne_of_gt x.property]

/-- Exact switching bijection: one independent bit per disagreement region. -/
def sortingFiberEquivBits {d m : ℕ} (w : WeakOrderedPair d m) :
    SortingFiber w ≃ (BandComponent w → Bool) where
  toFun := ownership
  invFun := fromOwnership w
  left_inv := fromOwnership_ownership
  right_inv := ownership_fromOwnership

theorem sortingFiber_card {d m : ℕ} (w : WeakOrderedPair d m) :
    Fintype.card (SortingFiber w) = 2 ^ clusterCount w := by
  rw [Fintype.card_congr (sortingFiberEquivBits w), Fintype.card_fun]
  simp [clusterCount]

/-- Exact finite partition function at cluster weight 2. -/
theorem trimmed_square_eq_cluster_sum (d m : ℕ) :
    trimmedCount d m ^ 2 = ∑ w : WeakOrderedPair d m, 2 ^ clusterCount w := by
  have h := Fintype.card_congr (Equiv.sigmaFiberEquiv
    (sortProfiles (d := d) (m := m)))
  rw [Fintype.card_sigma, Fintype.card_prod] at h
  change (∑ w : WeakOrderedPair d m, Fintype.card (SortingFiber w)) =
    trimmedCount d m * trimmedCount d m at h
  simpa only [sortingFiber_card, pow_two] using h.symm

/-- Sorting uniform independent pairs weights each ordered pair by 2^c.
The identity holds for every real observable of the component count. -/
theorem cluster_observable_change_of_ensemble (d m : ℕ) (f : ℕ → ℝ) :
    (∑ p : TrimmedProfile d m × TrimmedProfile d m, f (clusterCount (sortProfiles p))) =
      ∑ w : WeakOrderedPair d m, (2 : ℝ) ^ clusterCount w * f (clusterCount w) := by
  have h := (Equiv.sigmaFiberEquiv (sortProfiles (d := d) (m := m))).sum_comp
    (fun p => f (clusterCount (sortProfiles p)))
  rw [Fintype.sum_sigma] at h
  rw [← h]
  apply Finset.sum_congr rfl
  intro w _
  change (∑ p : SortingFiber w, f (clusterCount (sortProfiles p.val))) = _
  calc
    _ = ∑ _p : SortingFiber w, f (clusterCount w) := by
      apply Finset.sum_congr rfl
      intro p _
      rw [p.property]
    _ = _ := by simp [sortingFiber_card]

/-- Average of 2^c under the UNIFORM ordered-pair ensemble. It is not the
mean cluster count, nor an average under independently sampled profiles. -/
def clusterExponentialMoment (d m : ℕ) : ℝ :=
  (∑ w : WeakOrderedPair d m, (2 : ℝ) ^ clusterCount w) /
    (fullSupportCount d m : ℝ)

/-- Weak ordering is exactly the logarithm of a cluster exponential moment. -/
theorem weakOrderingCost_eq_log_cluster_moment (d m : ℕ) (hm : 0 < m) :
    weakOrderingCost d m = Real.log (clusterExponentialMoment d m) := by
  have hsum : (∑ w : WeakOrderedPair d m, (2 : ℝ) ^ clusterCount w) =
      (trimmedCount d m : ℝ) ^ 2 := by
    exact_mod_cast (trimmed_square_eq_cluster_sum d m).symm
  have hH : (trimmedCount d m : ℝ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (trimmedCount_pos d m hm)
  have hQ : (fullSupportCount d m : ℝ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (fullSupportCount_pos d m hm)
  simp only [clusterExponentialMoment, hsum, Real.log_div (pow_ne_zero 2 hH) hQ,
    Real.log_pow, weakOrderingCost]
  norm_num

/-- Exact inverse-moment estimator under the independent-profile ensemble.
Small values may still have high relative sampling error; this is not an
automatic efficient approximation algorithm. -/
theorem independent_inverse_cluster_moment (d m : ℕ) :
    (∑ p : TrimmedProfile d m × TrimmedProfile d m,
      ((2 : ℝ) ^ clusterCount (sortProfiles p))⁻¹) /
        (trimmedCount d m : ℝ) ^ 2 =
      (fullSupportCount d m : ℝ) / (trimmedCount d m : ℝ) ^ 2 := by
  rw [cluster_observable_change_of_ensemble d m (fun c => ((2 : ℝ) ^ c)⁻¹)]
  have hcard : Fintype.card (WeakOrderedPair d m) = fullSupportCount d m :=
    (Fintype.card_congr (fullSupportPairEquivWeak d m)).symm
  simp [hcard]

/-- Elementary Jensen bounds: the log arithmetic mean lies between the
uniform mean log and the size-weighted mean log. -/
theorem log_mean_bounds {ι : Type*} [Fintype ι] [Nonempty ι]
    (f : ι → ℝ) (hf : ∀ i, 0 < f i) :
    (∑ i, Real.log (f i)) / (Fintype.card ι : ℝ) ≤
        Real.log ((∑ i, f i) / (Fintype.card ι : ℝ)) ∧
      Real.log ((∑ i, f i) / (Fintype.card ι : ℝ)) ≤
        (∑ i, f i * Real.log (f i)) / (∑ i, f i) := by
  have hN : (0 : ℝ) < (Fintype.card ι : ℝ) := by exact_mod_cast Fintype.card_pos
  have hS : (0 : ℝ) < ∑ i, f i := Finset.sum_pos (fun i _ => hf i) Finset.univ_nonempty
  have hlo := strictConcaveOn_log_Ioi.concaveOn.le_map_sum
    (t := Finset.univ) (w := fun _ : ι => (Fintype.card ι : ℝ)⁻¹) (p := f)
    (fun _ _ => le_of_lt (inv_pos.mpr hN))
    (by simp [hN.ne']) (fun i _ => hf i)
  simp only [smul_eq_mul, ← Finset.mul_sum] at hlo
  have hhi := strictConcaveOn_log_Ioi.concaveOn.le_map_sum
    (t := Finset.univ) (w := fun i => f i / ∑ j, f j) (p := fun i => (f i)⁻¹)
    (fun i _ => le_of_lt (div_pos (hf i) hS))
    (by rw [← Finset.sum_div]; exact div_self hS.ne') (fun i _ => inv_pos.mpr (hf i))
  have hr : (∑ i, f i / (∑ j, f j) * (f i)⁻¹) =
      (Fintype.card ι : ℝ) / (∑ j, f j) := by
    simp_rw [div_mul_eq_mul_div, mul_inv_cancel₀ (hf _).ne']
    simp [div_eq_mul_inv]
  have hl : (∑ i, f i / (∑ j, f j) * -Real.log (f i)) =
      -(∑ i, f i * Real.log (f i)) / (∑ j, f j) := by
    simp only [mul_neg, div_mul_eq_mul_div, Finset.sum_neg_distrib, ← Finset.sum_div,
      neg_div]
  simp only [smul_eq_mul, Real.log_inv] at hhi
  rw [hr, hl, Real.log_div hN.ne' hS.ne'] at hhi
  simp only [neg_div] at hhi
  constructor
  · simpa only [inv_mul_eq_div] using hlo
  · rw [Real.log_div hS.ne' hN.ne']
    linarith

def orderedMeanClusters (d m : ℕ) : ℝ :=
  (∑ w : WeakOrderedPair d m, (clusterCount w : ℝ)) / (fullSupportCount d m : ℝ)

def independentMeanClusters (d m : ℕ) : ℝ :=
  (∑ p : TrimmedProfile d m × TrimmedProfile d m,
    (clusterCount (sortProfiles p) : ℝ)) / (trimmedCount d m : ℝ) ^ 2

/-- A finite two-sided entropy bound with the ensembles made explicit.
An area bound for the independent mean is sufficient, but is NOT proved
here and need not be necessary for the proposed area law. -/
theorem weakOrderingCost_mean_cluster_bounds (d m : ℕ) (hm : 0 < m) :
    Real.log 2 * orderedMeanClusters d m ≤ weakOrderingCost d m ∧
      weakOrderingCost d m ≤ Real.log 2 * independentMeanClusters d m := by
  have hcard : Fintype.card (WeakOrderedPair d m) = fullSupportCount d m :=
    (Fintype.card_congr (fullSupportPairEquivWeak d m)).symm
  haveI : Nonempty (WeakOrderedPair d m) := Fintype.card_pos_iff.mp
    (hcard ▸ fullSupportCount_pos d m hm)
  have h := log_mean_bounds (fun w : WeakOrderedPair d m => (2 : ℝ) ^ clusterCount w)
    (fun _ => by positivity)
  have hsum : (∑ w : WeakOrderedPair d m, (2 : ℝ) ^ clusterCount w) =
      (trimmedCount d m : ℝ) ^ 2 := by
    exact_mod_cast (trimmed_square_eq_cluster_sum d m).symm
  have hcost : Real.log ((∑ w : WeakOrderedPair d m, (2 : ℝ) ^ clusterCount w) /
      (fullSupportCount d m : ℝ)) = weakOrderingCost d m :=
    (weakOrderingCost_eq_log_cluster_moment d m hm).symm
  rw [hcard] at h
  rw [hcost] at h
  simp only [Real.log_pow] at h
  have hobs := cluster_observable_change_of_ensemble d m (fun c => (c : ℝ))
  constructor
  · convert h.1 using 1
    unfold orderedMeanClusters
    rw [← Finset.sum_mul]
    ring
  · convert h.2 using 1
    unfold independentMeanClusters
    rw [hobs, hsum]
    simp_rw [← mul_assoc]
    rw [← Finset.sum_mul]
    ring

end
end CausalAlgebraicGeometry.CAGOrderingClusters
