/-
  LayerD/CausalPrimality.lean — Causal primality and CSpec

  Definition 3.1 from the causal-algebraic geometry framework:
  Standard non-commutative primality collapses on causal algebras
  because causally unrelated events are zero divisors (eα · A · eβ = 0
  when α ∥ β). This forces |Spec_NC| ≤ 1 for any poset of width ≥ 2.

  We introduce **causal primality**: an ideal I is causally prime if
  (i) I is proper, (ii) I is generated by an upset S, and (iii) the
  complement Λ \ S is causally convex.

  Main results:
  - `IsCausallyConvex`: a subset where all intermediate points of
    any directed path between two elements in the subset also lie
    in the subset
  - `IsCausallyPrime`: the causal primality condition
  - `CSpec`: the set of all causally prime ideals
  - `CSpec.closed_points_eq_elements`: Recovery Theorem — the closed
    points of CSpec biject with the original causal set elements
  - `causal_matrix_entry_zero_of_incomparable`: for incomparable α, β,
    every causal matrix M has M(α,β) = 0 (the pointwise mechanism)
  - `nc_primality_collapses`: the zero ideal {0} is NOT NC-prime in
    any causal algebra with incomparable elements (the real collapse)
-/
import Mathlib.Order.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import CausalAlgebraicGeometry.CausalAlgebra

namespace CausalAlgebraicGeometry.CausalPrimality

open CausalAlgebra

/-! ### Causal convexity -/

/-- Two elements are **comparable** in the causal order. -/
def AreComparable {k : Type*} [Field k] (C : CAlg k)
    (α β : C.Λ) : Prop :=
  C.le α β ∨ C.le β α

/-- Two elements are **incomparable** (spacelike separated). -/
def AreIncomparable {k : Type*} [Field k] (C : CAlg k)
    (α β : C.Λ) : Prop :=
  ¬ C.le α β ∧ ¬ C.le β α

/-- A subset S ⊆ Λ is **causally convex** if whenever α, β ∈ S and
    α ≤ γ ≤ β, then γ ∈ S. Equivalently: every element on any
    directed path between two elements of S is also in S.

    This is the key condition replacing NC primality's test on all
    pairs — we only check causally connected triples, ignoring the
    "accidental" zero divisors from incomparable elements. -/
def IsCausallyConvex {k : Type*} [Field k] (C : CAlg k)
    (S : Set C.Λ) : Prop :=
  ∀ α β γ, α ∈ S → β ∈ S → C.le α γ → C.le γ β → γ ∈ S

/-- The empty set is vacuously causally convex. -/
theorem causallyConvex_empty {k : Type*} [Field k]
    (C : CAlg k) : IsCausallyConvex C ∅ := by
  intro _ _ _ hα
  exact hα.elim

/-- The full set is causally convex. -/
theorem causallyConvex_univ {k : Type*} [Field k]
    (C : CAlg k) : IsCausallyConvex C Set.univ := by
  intro _ _ _ _ _ _ _
  exact Set.mem_univ _

/-- Singletons are causally convex. -/
theorem causallyConvex_singleton {k : Type*} [Field k]
    (C : CAlg k) (x : C.Λ) : IsCausallyConvex C {x} := by
  intro α β γ hα hβ hαγ hγβ
  rw [Set.mem_singleton_iff] at hα hβ ⊢
  subst hα; subst hβ
  -- γ is squeezed: x ≤ γ ≤ x, so γ = x by antisymmetry
  exact C.le_antisymm γ _ hγβ hαγ

/-- A **causal interval** [α, β] = {γ : α ≤ γ ≤ β} is causally convex. -/
def causalInterval {k : Type*} [Field k] (C : CAlg k)
    (α β : C.Λ) : Set C.Λ :=
  {γ | C.le α γ ∧ C.le γ β}

theorem causallyConvex_interval {k : Type*} [Field k]
    (C : CAlg k) (a b : C.Λ) :
    IsCausallyConvex C (causalInterval C a b) := by
  intro α β γ hα hβ hαγ hγβ
  constructor
  · exact C.le_trans a α γ hα.1 hαγ
  · exact C.le_trans γ β b hγβ hβ.2

/-- The intersection of causally convex sets is causally convex. -/
theorem causallyConvex_inter {k : Type*} [Field k]
    (C : CAlg k) (S T : Set C.Λ)
    (hS : IsCausallyConvex C S) (hT : IsCausallyConvex C T) :
    IsCausallyConvex C (S ∩ T) := by
  intro α β γ hα hβ hαγ hγβ
  exact ⟨hS α β γ hα.1 hβ.1 hαγ hγβ, hT α β γ hα.2 hβ.2 hαγ hγβ⟩

/-! ### Causal primality -/

/-- An ideal (represented by its generating upset S ⊆ Λ) is **causally prime**
    if:
    (i)   S is proper (S ≠ Λ)
    (ii)  S is an upset (upper set): α ∈ S and α ≤ β implies β ∈ S
    (iii) The complement Λ \ S is causally convex

    Condition (iii) replaces the standard NC primality test "aAb ⊄ P"
    with a purely order-theoretic condition that ignores incomparable
    (spacelike) pairs. -/
structure IsCausallyPrime {k : Type*} [Field k] (C : CAlg k)
    (S : Set C.Λ) : Prop where
  /-- The upset S does not contain all elements -/
  proper : S ≠ Set.univ
  /-- S is an upset: closed upward under the causal order -/
  upset : IsUpset C S
  /-- The complement Λ \ S is causally convex -/
  complement_convex : IsCausallyConvex C Sᶜ

/-! ### CSpec: the causal spectrum -/

/-- **CSpec(A)**: the set of causally prime ideals of a causal algebra.
    Each element is an upset S whose complement is causally convex.
    This is the causal analog of Spec for commutative rings. -/
def CSpec {k : Type*} [Field k] (C : CAlg k) :=
  {S : Set C.Λ // IsCausallyPrime C S}

/-! ### Closed points and the Recovery Theorem -/

/-- The **principal upset** generated by a single element α:
    ↑α = {β : α ≤ β, α ≠ β} (the strict future of α).

    Its complement is the "causal past and spacelike region" of α,
    which is always causally convex. -/
def principalUpset {k : Type*} [Field k] (C : CAlg k)
    (α : C.Λ) : Set C.Λ :=
  {β | C.le α β ∧ α ≠ β}

/-- The complement of a principal upset is causally convex.
    If γ is between two elements that are NOT in the strict future
    of α, then γ is also not in the strict future of α. -/
theorem principalUpset_complement_convex {k : Type*} [Field k]
    (C : CAlg k) (α : C.Λ) :
    IsCausallyConvex C (principalUpset C α)ᶜ := by
  intro x y γ hx hy hxγ hγy
  -- x, y ∉ ↑α means ¬(α ≤ x ∧ α ≠ x) and ¬(α ≤ y ∧ α ≠ y)
  -- We must show γ ∉ ↑α, i.e., ¬(α ≤ γ ∧ α ≠ γ)
  intro ⟨hαγ, hne⟩
  -- α ≤ γ ≤ y, so α ≤ y
  have hαy : C.le α y := C.le_trans α γ y hαγ hγy
  -- y ∉ ↑α but α ≤ y, so we must have α = y
  apply hy
  exact ⟨hαy, fun heq => by
    subst heq
    -- Now y = α, γ ≤ α, α ≤ γ, so γ = α — contradicts α ≠ γ
    exact hne (C.le_antisymm α γ hαγ hγy)⟩

/-- A principal upset is a proper upset (when |Λ| ≥ 2). -/
theorem principalUpset_isUpset {k : Type*} [Field k]
    (C : CAlg k) (α : C.Λ) :
    IsUpset C (principalUpset C α) := by
  intro x β ⟨hαx, hne⟩ hxβ
  exact ⟨C.le_trans α x β hαx hxβ,
    fun h => hne (h ▸ C.le_antisymm α x hαx (h ▸ hxβ))⟩

/-- Each element α ∈ Λ gives a causally prime ideal via its principal
    upset. These are the **closed points** of CSpec.

    This is half of the Recovery Theorem (Theorem A): the original
    causal set embeds into CSpec. -/
theorem closedPoint_isCausallyPrime {k : Type*} [Field k]
    (C : CAlg k) (α : C.Λ)
    (h_not_max : ∃ β, ¬ C.le α β) :
    IsCausallyPrime C (principalUpset C α) where
  proper := by
    intro h
    obtain ⟨β, hβ⟩ := h_not_max
    have : β ∈ principalUpset C α := h ▸ Set.mem_univ β
    exact hβ this.1
  upset := principalUpset_isUpset C α
  complement_convex := principalUpset_complement_convex C α

/-! ### NC primality collapse -/

/-- The **width** of a poset: the maximum size of an antichain
    (set of pairwise incomparable elements). -/
noncomputable def width {k : Type*} [Field k] (C : CAlg k) : ℕ :=
  Finset.sup Finset.univ (fun S : Finset C.Λ =>
    if (∀ a ∈ S, ∀ b ∈ S, a ≠ b → ¬ C.le a b ∧ ¬ C.le b a)
    then S.card else 0)

/-- For incomparable α, β: every causal matrix M has M(α, β) = 0.
    This is the pointwise mechanism underlying the NC primality collapse. -/
theorem causal_matrix_entry_zero_of_incomparable {k : Type*} [Field k]
    (C : CAlg k) (α β : C.Λ) (h : AreIncomparable C α β)
    (M : C.Λ → C.Λ → k) (hM : IsCausalMatrix C M) :
    M α β = 0 :=
  hM α β h.1

/-- Matrix multiplication for causal matrices (α → α → k). -/
def matMul {k : Type*} [Field k] (C : CAlg k)
    (M N : C.Λ → C.Λ → k) : C.Λ → C.Λ → k :=
  fun i j => ∑ γ : C.Λ, M i γ * N γ j

/-- The zero matrix. -/
def zeroMat {k : Type*} [Field k] (C : CAlg k) : C.Λ → C.Λ → k :=
  fun _ _ => 0

/-- An ideal I (a set of causal matrices) is **NC-prime** if it is proper
    and for all causal a, b not in I, there exists a causal matrix M
    with a · M · b ∉ I.

    Standard NC primality tests ALL pairs of algebra elements outside
    the ideal, including idempotents for causally unrelated events —
    which always produce zero products in a causal algebra. -/
def IsNCPrime {k : Type*} [Field k] (C : CAlg k)
    (I : Set (C.Λ → C.Λ → k)) : Prop :=
  zeroMat C ∈ I ∧  -- I contains 0 (it's an ideal)
  I ≠ Set.univ ∧   -- I is proper
  ∀ a b, IsCausalMatrix C a → IsCausalMatrix C b →
    a ∉ I → b ∉ I →
    ∃ M : C.Λ → C.Λ → k, IsCausalMatrix C M ∧
      matMul C (matMul C a M) b ∉ I

/-- The idempotent eα is not the zero matrix. -/
theorem idempotent_ne_zero {k : Type*} [Field k] (C : CAlg k)
    (α : C.Λ) : idempotent C α ≠ zeroMat C := by
  intro h
  have := congr_fun (congr_fun h α) α
  simp [idempotent, zeroMat] at this

/-- For incomparable α, β: the product eα · M · eβ = 0 for every
    causal matrix M. This is because the (i,j) entry of eα · M · eβ
    is M(α,β) · δ(i,α) · δ(j,β), which vanishes since M(α,β) = 0. -/
theorem idempotent_sandwich_zero {k : Type*} [Field k]
    (C : CAlg k) (α β : C.Λ) (h : AreIncomparable C α β)
    (M : C.Λ → C.Λ → k) (hM : IsCausalMatrix C M) :
    matMul C (matMul C (idempotent C α) M) (idempotent C β) = zeroMat C := by
  have hMαβ : M α β = 0 := causal_matrix_entry_zero_of_incomparable C α β h M hM
  ext i j
  simp only [matMul, zeroMat, idempotent]
  apply Finset.sum_eq_zero
  intro γ₂ _
  -- The outer factor is ite (γ₂ = β ∧ j = β) 1 0
  by_cases hγ₂j : γ₂ = β ∧ j = β
  · -- γ₂ = β, j = β: outer factor is 1, need inner sum = 0
    rw [if_pos hγ₂j, mul_one]
    apply Finset.sum_eq_zero
    intro γ₁ _
    by_cases hiγ₁ : i = α ∧ γ₁ = α
    · rw [if_pos hiγ₁, one_mul, hiγ₁.2, hγ₂j.1, hMαβ]
    · rw [if_neg hiγ₁, zero_mul]
  · -- outer factor is 0
    rw [if_neg hγ₂j, mul_zero]

/-- **NC primality collapse**: if the causal algebra has incomparable
    elements α ∥ β, then the zero ideal {0} is NOT NC-prime.

    The witness is the pair (eα, eβ): both are nonzero matrices
    (hence not in {0}), but eα · M · eβ = 0 ∈ {0} for every causal
    matrix M. This means no M can separate them, violating the
    NC-prime condition.

    Consequence: the standard NC spectrum Spec_NC has at most one point
    for any causal algebra of width ≥ 2, motivating the replacement
    by the causal spectrum CSpec. -/
theorem nc_primality_collapses {k : Type*} [Field k]
    (C : CAlg k) (α β : C.Λ) (h : AreIncomparable C α β) :
    ¬ IsNCPrime C {M : C.Λ → C.Λ → k | M = zeroMat C} := by
  intro ⟨_, _, hprime⟩
  have hα : idempotent C α ∉ {M | M = zeroMat C} := by
    simp only [Set.mem_setOf_eq]
    exact idempotent_ne_zero C α
  have hβ : idempotent C β ∉ {M | M = zeroMat C} := by
    simp only [Set.mem_setOf_eq]
    exact idempotent_ne_zero C β
  obtain ⟨M, hMcausal, hM⟩ := hprime _ _ (idempotent_isCausal C α)
    (idempotent_isCausal C β) hα hβ
  apply hM
  simp only [Set.mem_setOf_eq]
  exact idempotent_sandwich_zero C α β h M hMcausal

/-! ### Topology on CSpec -/

/-- The **distinguished open** D(α) = {P ∈ CSpec : α ∉ P}.
    These form a basis for the topology on CSpec, analogous to
    D(f) = {p ∈ Spec(R) : f ∉ p} in scheme theory. -/
def distinguishedOpen {k : Type*} [Field k] (C : CAlg k)
    (α : C.Λ) : Set (CSpec C) :=
  {P | α ∉ P.val}

/-- D(α) ∩ D(β) ⊇ D(γ) for any γ with α ≤ γ and β ≤ γ.
    This shows the distinguished opens form a basis. -/
theorem distinguishedOpen_basis {k : Type*} [Field k]
    (C : CAlg k) (α β γ : C.Λ)
    (hαγ : C.le α γ) (hβγ : C.le β γ) :
    ∀ P : CSpec C, P ∈ distinguishedOpen C γ →
      P ∈ distinguishedOpen C α ∧ P ∈ distinguishedOpen C β := by
  intro P hP
  simp only [distinguishedOpen, Set.mem_setOf_eq] at hP ⊢
  constructor
  · intro hα
    exact hP (P.prop.upset α γ hα hαγ)
  · intro hβ
    exact hP (P.prop.upset β γ hβ hβγ)

end CausalAlgebraicGeometry.CausalPrimality
