/-
  CSpecActualSheaf.lean — A genuine Mathlib sheaf on the causal spectrum.

  The earlier `CSpecSheaf` file proves the algebraic locality statement for
  corner matrices.  This file supplies the missing categorical layer:

  * a Zariski-style topology on `CSpec C`, generated by the basic opens
      D(a) = { P | a ∉ P };
  * a dependent fibre over P consisting of causal corner matrices supported
    on the convex complement of P;
  * an actual `TopCat.Sheaf (Type _)` whose restriction maps are restriction
    of dependent functions and whose sheaf condition is checked by Mathlib.

  This is deliberately a sheaf of types.  Promoting it to a sheaf of rings
  requires first packaging `CornerElt` as a bundled (generally
  noncommutative) ring; the topology and sheaf-condition layer below will not
  need to change.
-/
import Mathlib.Topology.Sheaves.SheafOfFunctions
import CausalAlgebraicGeometry.CSpecSheaf

namespace CausalAlgebraicGeometry.CSpecActualSheaf

open CategoryTheory Opposite TopologicalSpace
open CausalAlgebra CausalPrimality CSpecSheaf

universe u

variable {k : Type u} [Field k] (C : CAlg k)

/-- The Zariski-style basic subset `D(a) = {P | a ∉ P}` of the causal
spectrum. -/
def basicOpenSet (a : C.Λ) : Set (CSpec C) :=
  {P | a ∉ P.1}

/-- The topology on `CSpec C` generated by the basic opens `D(a)`. -/
def cspecTopology : TopologicalSpace (CSpec C) :=
  TopologicalSpace.generateFrom (Set.range (basicOpenSet C))

/-- The causal spectrum bundled with its generated topology. -/
def CSpecTop : TopCat :=
  @TopCat.of (CSpec C) (cspecTopology C)

/-- A generator `D(a)` as an actual open of `CSpecTop C`. -/
def basicOpen (a : C.Λ) : Opens (CSpecTop C) where
  carrier := basicOpenSet C a
  is_open' := isOpen_generateFrom_of_mem ⟨a, rfl⟩

@[simp]
theorem mem_basicOpen_iff (a : C.Λ) (P : CSpecTop C) :
    P ∈ basicOpen C a ↔ a ∉ P.1 :=
  Iff.rfl

/-- The finite causal region complementary to a causal prime. -/
noncomputable def primeComplementFinset (P : CSpec C) : Finset C.Λ :=
  by
    classical
    exact Finset.univ.filter fun a => a ∉ P.1

@[simp]
theorem mem_primeComplementFinset_iff (P : CSpec C) (a : C.Λ) :
    a ∈ primeComplementFinset C P ↔ a ∉ P.1 := by
  classical
  simp [primeComplementFinset]

/-- The complement of every point of `CSpec` is causally convex, now in the
finite-set formulation used by corner sections. -/
theorem primeComplementFinset_isConvex (P : CSpec C) :
    IsConvex C (primeComplementFinset C P) := by
  intro a ha b hb x hax hxb
  rw [mem_primeComplementFinset_iff] at ha hb ⊢
  exact P.2.complement_convex a b x ha hb hax hxb

/-- The stalk fibre assigned to a causal prime: causal matrices supported on
the convex causal region outside that prime. -/
def causalCornerFiber (P : CSpecTop C) : Type _ :=
  CornerElt C (primeComplementFinset C P)

/-- The genuine Mathlib sheaf of dependent causal-corner fibres on `CSpec`.

A section on an open `U` assigns a corner element to every `P ∈ U`.
Restriction is ordinary function restriction, and compatible local sections
glue pointwise. -/
noncomputable def causalCornerSheaf : TopCat.Sheaf (Type _) (CSpecTop C) :=
  TopCat.sheafToTypes (CSpecTop C) (causalCornerFiber C)

/-- The categorical sheaf condition is part of the constructed object, rather
than represented by a bespoke locality predicate. -/
theorem causalCornerSheaf_isSheaf :
    (causalCornerSheaf C).presheaf.IsSheaf :=
  (causalCornerSheaf C).2

@[simp]
theorem causalCornerSheaf_obj (U : Opens (CSpecTop C)) :
    (causalCornerSheaf C).presheaf.obj (op U) =
      (∀ P : U, causalCornerFiber C P) :=
  rfl

/-- Restriction maps really are restriction of dependent functions. -/
@[simp]
theorem causalCornerSheaf_restrict_apply
    {U V : Opens (CSpecTop C)} (hVU : V ≤ U)
    (s : (causalCornerSheaf C).presheaf.obj (op U)) (P : V) :
    (causalCornerSheaf C).presheaf.map (homOfLE hVU).op s P =
      s ⟨P.1, hVU P.2⟩ :=
  rfl

/-- The old corner-product locality theorem is available in every new stalk
fibre because a causal prime has convex complement. -/
theorem fibre_product_sum_restrict (P : CSpec C)
    (M N : causalCornerFiber C P) (a b : C.Λ)
    (ha : a ∈ primeComplementFinset C P)
    (hb : b ∈ primeComplementFinset C P) :
    (cornerMul C M N).mat a b =
      ∑ x ∈ primeComplementFinset C P, M.mat a x * N.mat x b :=
  product_sum_restrict C (primeComplementFinset_isConvex C P) M N a b ha hb

end CausalAlgebraicGeometry.CSpecActualSheaf
