/-
  RecoveryLimitations.lean — Precise limitations of the recovery theorem.

  Documents exactly what works and what fails for poset recovery from CSpec.

  1. Non-strict principal filter ↑≤α = {β : α ≤ β} is ALWAYS injective (T0Recovery.lean)
     BUT ↑≤(minimum) = Λ is not proper, hence not a CSpec point.

  2. Strict principal upset ↑α = {β : α < β} gives a CSpec point for non-maximal α
     (closedPoint_isCausallyPrime in CausalPrimality.lean)
     BUT injectivity needs T₀ (V-poset counterexample in RecoveryCounterexample.lean).

  3. The "closed points" language from scheme theory does NOT apply correctly:
     in the topology generated by D(α) = {P : α ∉ P}, the specialization order
     makes MAXIMAL-element upsets closed and MINIMAL-element upsets generic.
     This is the opposite of what the paper claims.

  These are FUNDAMENTAL LIMITATIONS of the CSpec analogy with Spec(R).
  The paper should acknowledge them explicitly.

  Zero sorry.
-/
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Tactic

namespace CausalAlgebraicGeometry.RecoveryLimitations

/-! ## The minimum-element problem -/

/-- In a 3-element chain 0 < 1 < 2, the non-strict filter of the minimum is everything. -/
def chainLe : Fin 3 → Fin 3 → Prop := fun a b => a.val ≤ b.val
instance : DecidableRel chainLe := fun a b => inferInstanceAs (Decidable (a.val ≤ b.val))

def nonStrictFilter (a : Fin 3) : Finset (Fin 3) :=
  Finset.univ.filter fun b => chainLe a b

/-- ↑≤0 = {0, 1, 2} = Fin 3 (the whole set). NOT proper. -/
theorem min_filter_is_univ : nonStrictFilter 0 = Finset.univ := by native_decide

/-- ↑≤1 = {1, 2}. Proper. -/
theorem mid_filter_proper : nonStrictFilter 1 ≠ Finset.univ := by native_decide

/-- ↑≤2 = {2}. Proper. -/
theorem max_filter_proper : nonStrictFilter 2 ≠ Finset.univ := by native_decide

/-- The minimum's filter equals the universe — it cannot be a "proper" CSpec point. -/
theorem minimum_not_proper :
    nonStrictFilter 0 = Finset.univ ∧
    nonStrictFilter 1 ≠ Finset.univ ∧
    nonStrictFilter 2 ≠ Finset.univ :=
  ⟨min_filter_is_univ, mid_filter_proper, max_filter_proper⟩

/-! ## The specialization-order problem -/

/-- In the chain, strict upsets are: ↑0 = {1,2}, ↑1 = {2}, ↑2 = ∅. -/
def strictUpset (a : Fin 3) : Finset (Fin 3) :=
  Finset.univ.filter fun b => chainLe a b ∧ a ≠ b

theorem upset_0 : strictUpset 0 = {1, 2} := by native_decide
theorem upset_1 : strictUpset 1 = {2} := by native_decide
theorem upset_2 : strictUpset 2 = ∅ := by native_decide

/-- ↑0 ⊃ ↑1 ⊃ ↑2: larger upsets = smaller elements = more generic.
    |↑0| = 2, |↑1| = 1, |↑2| = 0: the minimum has the largest upset. -/
theorem upset_sizes :
    (strictUpset 0).card = 2 ∧ (strictUpset 1).card = 1 ∧ (strictUpset 2).card = 0 := by
  exact ⟨by native_decide, by native_decide, by native_decide⟩

/-- The maximum (element 2) has the SMALLEST (empty) upset.
    In the CSpec topology, this makes it the CLOSED point — opposite to what
    the paper claims when it says "α ↦ ↑α embeds the poset as closed points." -/
theorem max_is_closed_min_is_generic :
    (strictUpset 2).card = 0 ∧ (strictUpset 0).card = 2 := by
  exact ⟨by native_decide, by native_decide⟩

/-! ## What IS correctly proved -/

-- Despite the limitations above, the non-strict filter map IS always injective
-- (from T0Recovery.lean). The correct statement for the paper is:
--
-- "Every finite poset can be recovered from its principal filters.
--  The map α ↦ {β : α ≤ β} is injective, but these filters are NOT
--  all CSpec points (the minimum's filter is improper), and they are
--  NOT closed points in the CSpec topology (the specialization order
--  makes minimal-element points generic, not closed)."
--
-- The paper should SEPARATE:
-- 1. Poset recovery (via principal filters — always works)
-- 2. CSpec as a topological space (uses strict upsets of non-maximal elements)
-- 3. These are DIFFERENT constructions and should not be conflated.

end CausalAlgebraicGeometry.RecoveryLimitations
